# Pandas

In [ ]:
pip install pandas numpy

In [2]:
import pandas as pd
import numpy as np

# Series

Creation

Tata        100
Birla       200
Wipro       300
ITC         400

In [6]:
mylist1 = [100,200,300,400]
indexlist = ['Tata', 'Birla', 'Wipro', 'ITC']

In [3]:
ps1 = pd.Series(mylist1)
print(type(ps1))
print(ps1)
print(ps1[2])

<class 'pandas.core.series.Series'>
0    100
1    200
2    300
3    400
dtype: int64
300

In [7]:
print(ps1.index)
print(ps1.shape)
print(ps1.ndim)
print(ps1.size)
print(ps1.dtype)
print(ps1.values)
print(type(ps1.values))

RangeIndex(start=0, stop=4, step=1)
(4,)
1
4
int64
[100 200 300 400]
<class 'numpy.ndarray'>

In [8]:
ps2 = pd.Series(mylist1, index=indexlist)
print(ps2)
print(ps2.index)
print(ps2['Wipro'])

Tata     100
Birla    200
Wipro    300
ITC      400
dtype: int64
Index(['Tata', 'Birla', 'Wipro', 'ITC'], dtype='object')
300

In [9]:
r = ps2['Tata']
print(type(r))

<class 'numpy.int64'>

In [10]:
ps2 = pd.Series(mylist1, index=indexlist, dtype=np.int32)
print(ps2)

Tata     100
Birla    200
Wipro    300
ITC      400
dtype: int32

In [11]:
ps2.dtype

dtype('int32')

In [12]:
np.random.seed(23)

n10 = np.random.randint(low=10, high=100, size=10)
n10

array([93, 50, 83, 64, 41, 86, 49, 35, 61, 16])

In [13]:
ps3 = pd.Series(n10)
ps3

0    93
1    50
2    83
3    64
4    41
5    86
6    49
7    35
8    61
9    16
dtype: int32

In [14]:
ps4 = pd.Series(n10, index=list('abcdefghij'))
ps4

a    93
b    50
c    83
d    64
e    41
f    86
g    49
h    35
i    61
j    16
dtype: int32

In [ ]:
ps5 = pd.Series(n10, index=list('abcdefghi'))  # Error
ps5

Tata        100
Birla       200
Wipro       300
ITC         400

In [48]:
md1 = {'Tata':100, 'Birla':200, 'Wipro':300, 999:400}

ps6 = pd.Series(md1)
ps6

Tata     100
Birla    200
Wipro    300
999      400
dtype: int64

In [16]:
ps6.index

Index(['Tata', 'Birla', 'Wipro', 999], dtype='object')

In [17]:
ps6[999]

400

In [49]:
print(type(ps6.index))

<class 'pandas.core.indexes.base.Index'>

In [50]:
print(type(ps6.index[0]))

<class 'str'>

In [51]:
print(type(ps6.index[-1]))

<class 'int'>

# Accessing a  Series

In [18]:
np.random.seed(23)
n10 = np.random.randint(low=10, high=100, size=10)
ps7 = pd.Series(n10, index=list('abcdefghij'))
print(ps7.index)
ps7

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

a    93
b    50
c    83
d    64
e    41
f    86
g    49
h    35
i    61
j    16
dtype: int32

In [19]:
ps7[0]

C:\Users\Edunet Foundation\AppData\Local\Temp\ipykernel_16100\2454248703.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ps7[0]

93

In [20]:
ps7['a']

93

In [21]:
ps7[2:7]  ##in numerical slice endpoint = False

c    83
d    64
e    41
f    86
g    49
dtype: int32

In [22]:
ps7['i':'c']  #  in labelled slice, endpoint=True

Series([], dtype: int32)

In [23]:
ps7['a']

93

In [24]:
type(ps7['a'])

numpy.int32

In [ ]:
type(ps7['b'])

In [25]:
ps7

a    93
b    50
c    83
d    64
e    41
f    86
g    49
h    35
i    61
j    16
dtype: int32

In [26]:
ps7[ [0,1,-2,-1]  ]

C:\Users\Edunet Foundation\AppData\Local\Temp\ipykernel_16100\2411164769.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ps7[ [0,1,-2,-1]  ]

a    93
b    50
i    61
j    16
dtype: int32

In [27]:
ps7[ ['a','b','i'] ]

a    93
b    50
i    61
dtype: int32

In [28]:
ps7

a    93
b    50
c    83
d    64
e    41
f    86
g    49
h    35
i    61
j    16
dtype: int32

In [29]:
mask = ps7 > 50
mask

a     True
b    False
c     True
d     True
e    False
f     True
g    False
h    False
i     True
j    False
dtype: bool

In [30]:
ps7[mask]

a    93
c    83
d    64
f    86
i    61
dtype: int32

In [31]:
ps7[ps7>50]

a    93
c    83
d    64
f    86
i    61
dtype: int32

# Data Frame

       Vol  Rev  HQ
Tata   100  75   'Mum'
Birla  200  175  'Kol'
Wipro  300  250  'Blr'
ITC    400  450  'Mum'
HCL    500  550  'NCR

In [32]:
mylist53 = [
    [100,75, 'Mum'],
    [200, 175, 'Kol'],
    [300, 250, 'Blr'],
    [400,450, 'Mum'],
    [500,550,'NCR']
]
row_index_list = ['Tata', 'Birla','Wipro','ITC','HCL']
col_index_list = ['Vol', 'Rev','HQ']

In [33]:
df1 = pd.DataFrame(mylist53)
print(type(df1))
print(df1)
print(df1.index)
print(df1.columns)

<class 'pandas.core.frame.DataFrame'>
     0    1    2
0  100   75  Mum
1  200  175  Kol
2  300  250  Blr
3  400  450  Mum
4  500  550  NCR
RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=3, step=1)

In [34]:
df1 = pd.DataFrame(mylist53, index=row_index_list, columns=col_index_list)
print(type(df1))
print(df1)
print(df1.index)
print(df1.columns)
print(df1.values)
print(type(df1.values))

<class 'pandas.core.frame.DataFrame'>
       Vol  Rev   HQ
Tata   100   75  Mum
Birla  200  175  Kol
Wipro  300  250  Blr
ITC    400  450  Mum
HCL    500  550  NCR
Index(['Tata', 'Birla', 'Wipro', 'ITC', 'HCL'], dtype='object')
Index(['Vol', 'Rev', 'HQ'], dtype='object')
[[100 75 'Mum']
 [200 175 'Kol']
 [300 250 'Blr']
 [400 450 'Mum']
 [500 550 'NCR']]
<class 'numpy.ndarray'>

       Vol  Rev  HQ
Tata   100  75   'Mum'
Birla  200  175  'Kol'
Wipro  300  250  'Blr'
ITC    400  450  'Mum'
HCL    500  550  'NCR

In [35]:
md1 = {'Vol':[100,200,300,400,500],  'Rev':[75,175,250,450,550], 
       'HQ':['Mum','Kol','Blr','Mum','NCR']}

In [36]:
df2 = pd.DataFrame(md1, index=row_index_list)
df2

       Vol  Rev   HQ
Tata   100   75  Mum
Birla  200  175  Kol
Wipro  300  250  Blr
ITC    400  450  Mum
HCL    500  550  NCR

In [37]:
col_index_list1 = ['Vol1', 'Rev1','HQ']
df3 = pd.DataFrame(md1, index=row_index_list,columns=col_index_list1)
df3

      Vol1 Rev1   HQ
Tata   NaN  NaN  Mum
Birla  NaN  NaN  Kol
Wipro  NaN  NaN  Blr
ITC    NaN  NaN  Mum
HCL    NaN  NaN  NCR

In [ ]:
# Data Frame Access

In [7]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [19]:
df1.info()

<class 'pandas.DataFrame'>
Index: 12 entries, Kolkata_FMCG to NCR_Infra
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Vol         11 non-null     float64
 1   Rev         12 non-null     float64
 2   Exp         12 non-null     int64
 3   Sector      12 non-null     str
 4   EmpCnt      12 non-null     int64
 5   HQ          12 non-null     str
 6   MNC         12 non-null     int64
 7   StockID     12 non-null     str
 8   GST         12 non-null     str
 9   Start Date  12 non-null     str
 10  Taxpaid     12 non-null     str
dtypes: float64(2), int64(3), str(6)
memory usage: 1.4+ KB

In [9]:
df1.describe()

              Vol         Rev         Exp        EmpCnt        MNC
count   12.000000   12.000000   12.000000     12.000000  12.000000
mean   938.666667  847.519167  676.500000   2254.166667   0.500000
std     27.503168   45.318608   86.561066   3443.674751   0.522233
min    899.000000  733.000000  605.000000    119.000000   0.000000
25%    924.000000  831.672500  615.000000   1245.500000   0.000000
50%    932.500000  853.350000  657.500000   1508.000000   0.500000
75%    957.000000  874.550000  679.250000   1710.250000   1.000000
max    992.000000  917.000000  899.000000  13023.000000   1.000000

In [10]:
df1.iloc[0,0] = np.nan
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,NaN,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921.0,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [11]:
df1.isnull()

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,True,False,False,False,False,False,False,False,False,False,False
NCR_Leagles,False,False,False,False,False,False,False,False,False,False,False
Bangalore_Systems,False,False,False,False,False,False,False,False,False,False,False
Chennai_Chemicals,False,False,False,False,False,False,False,False,False,False,False
Indi_Services,False,False,False,False,False,False,False,False,False,False,False
Chennai_Shipping,False,False,False,False,False,False,False,False,False,False,False
Eastern_Estates,False,False,False,False,False,False,False,False,False,False,False
Central_Services,False,False,False,False,False,False,False,False,False,False,False
Deccan_Sporting,False,False,False,False,False,False,False,False,False,False,False
Bangalore_Breweries,False,False,False,False,False,False,False,False,False,False,False
Bombay_Finance,False,False,False,False,False,False,False,False,False,False,False
NCR_Infra,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df1.isnull().sum()

Vol           1
Rev           0
Exp           0
Sector        0
EmpCnt        0
HQ            0
MNC           0
StockID       0
GST           0
Start Date    0
Taxpaid       0
dtype: int64

In [13]:
df1.isnull().sum().sum()

np.int64(1)

In [17]:
df1['Vol']

Kolkata_FMCG             NaN
NCR_Leagles            931.0
Bangalore_Systems      900.0
Chennai_Chemicals      966.0
Indi_Services          992.0
Chennai_Shipping       899.0
Eastern_Estates        945.0
Central_Services       934.0
Deccan_Sporting        931.0
Bangalore_Breweries    966.0
Bombay_Finance         954.0
NCR_Infra              921.0
Name: Vol, dtype: float64

In [20]:
df1[   ['Rev','HQ','Vol']   ]

                        Rev   HQ    Vol
Kolkata_FMCG         874.40  Kol    NaN
NCR_Leagles          863.50  NCR  931.0
Bangalore_Systems    881.60  Blr  900.0
Chennai_Chemicals    863.20  Che  966.0
Indi_Services        733.00  NCR  992.0
Chennai_Shipping     821.00  Che  899.0
Eastern_Estates      834.23  Kol  945.0
Central_Services     824.00  NCR  934.0
Deccan_Sporting      839.80  Hyd  931.0
Bangalore_Breweries  875.00  Blr  966.0
Bombay_Finance       917.00  Mum  954.0
NCR_Infra            843.50  NCR  921.0

In [7]:
df1.index

Index(['Kolkata_FMCG', 'NCR_Leagles', 'Bangalore_Systems', 'Chennai_Chemicals',
       'Indi_Services', 'Chennai_Shipping', 'Eastern_Estates',
       'Central_Services', 'Deccan_Sporting', 'Bangalore_Breweries',
       'Bombay_Finance'],
      dtype='object')

In [21]:
df1['NCR_Leagles': 'Bombay_Finance']

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$

In [22]:
df1['NCR_Leagles': 'NCR_Leagles']

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$

In [24]:
df1.Exp

Kolkata_FMCG           676
NCR_Leagles            605
Bangalore_Systems      650
Chennai_Chemicals      608
Indi_Services          633
Chennai_Shipping       899
Eastern_Estates        789
Central_Services       689
Deccan_Sporting        615
Bangalore_Breweries    674
Bombay_Finance         665
NCR_Infra              615
Name: Exp, dtype: int64

In [25]:
df1['EmpCnt']['Chennai_Shipping']

np.int64(899)

In [26]:
df1['Chennai_Shipping':'Chennai_Shipping']

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Chennai_Shipping,899.0,821.0,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0

In [27]:
df1['Chennai_Shipping':'Chennai_Shipping']['EmpCnt']

Chennai_Shipping    899
Name: EmpCnt, dtype: int64

In [28]:
df1['Chennai_Shipping':'Chennai_Shipping']['EmpCnt'].values[0]

np.int64(899)

In [29]:
df1['Chennai_Shipping':'Chennai_Shipping'][  ['EmpCnt', 'Exp', 'Vol'] ]

                  EmpCnt  Exp    Vol
Chennai_Shipping     899  899  899.0

In [30]:
df1.iloc[0]

Vol                NaN
Rev              874.4
Exp                676
Sector             Pub
EmpCnt            1379
HQ                 Kol
MNC                  0
StockID           KFMC
GST              Goods
Start Date    Jan 1920
Taxpaid         29.76$
Name: Kolkata_FMCG, dtype: object

In [31]:
df1.iloc[0,1]

np.float64(874.4)

In [32]:
df1.iloc[3:7]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$

In [33]:
df1.iloc[3:7, 4:7]

                   EmpCnt   HQ  MNC
Chennai_Chemicals    1656  Che    1
Indi_Services       13023  NCR    0
Chennai_Shipping      899  Che    1
Eastern_Estates      1873  Kol    1

In [34]:
df1.columns[4:7]

Index(['EmpCnt', 'HQ', 'MNC'], dtype='str')

In [35]:
df1.index[3:7]

Index(['Chennai_Chemicals', 'Indi_Services', 'Chennai_Shipping',
       'Eastern_Estates'],
      dtype='str')

In [36]:
df1.iloc[ [0,1,-1,-2,-3] ]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,NaN,874.4,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
NCR_Infra,921.0,843.5,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$
Bombay_Finance,954.0,917.0,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
Bangalore_Breweries,966.0,875.0,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$

In [37]:
df1.iloc[ [0,1,-1,-2,-3] ,   [0,-1,-2]   ]

                       Vol Taxpaid Start Date
Kolkata_FMCG           NaN  29.76$   Jan 1920
NCR_Leagles          931.0  38.78$   Feb 1960
NCR_Infra            921.0  34.27$   Feb 1920
Bombay_Finance       954.0   37.8$   Apr 1925
Bangalore_Breweries  966.0  19.65$   Oct 1971

In [38]:
df1.index

Index(['Kolkata_FMCG', 'NCR_Leagles', 'Bangalore_Systems', 'Chennai_Chemicals',
       'Indi_Services', 'Chennai_Shipping', 'Eastern_Estates',
       'Central_Services', 'Deccan_Sporting', 'Bangalore_Breweries',
       'Bombay_Finance', 'NCR_Infra'],
      dtype='str')

In [39]:
df1.columns

Index(['Vol', 'Rev', 'Exp', 'Sector', 'EmpCnt', 'HQ', 'MNC', 'StockID', 'GST',
       'Start Date', 'Taxpaid'],
      dtype='str')

In [40]:
df1.loc['NCR_Leagles']

Vol              931.0
Rev              863.5
Exp                605
Sector             Pub
EmpCnt            1935
HQ                 NCR
MNC                  0
StockID           NCRL
GST           Services
Start Date    Feb 1960
Taxpaid         38.78$
Name: NCR_Leagles, dtype: object

In [41]:
df1.loc['NCR_Leagles', 'EmpCnt']

np.int64(1935)

In [42]:
df1.loc['NCR_Leagles': 'Chennai_Chemicals':2]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Chennai_Chemicals,966.0,863.2,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$

In [43]:
df1.loc['NCR_Leagles': 'Chennai_Chemicals':2,  'Exp':'GST']

                   Exp Sector  EmpCnt   HQ  MNC StockID       GST
NCR_Leagles        605    Pub    1935  NCR    0    NCRL  Services
Chennai_Chemicals  608    Pub    1656  Che    1    CHEM     Goods

In [44]:
df1.loc[['NCR_Leagles','Chennai_Chemicals','Bombay_Finance']]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Chennai_Chemicals,966.0,863.2,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Bombay_Finance,954.0,917.0,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$

In [45]:
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,NaN,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921.0,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [46]:
df1.loc['Bombay_Sporting':'Bangalore_Breweries', ['Exp','GST','Sector'] ]

KeyError: "Cannot get left slice bound for non-monotonic index with a missing label 'Bombay_Sporting'. Either sort the index or specify an existing label."

Conditional Access

In [47]:
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,NaN,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921.0,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [48]:
mask = df1.Sector == 'Pub'
mask

Kolkata_FMCG            True
NCR_Leagles             True
Bangalore_Systems      False
Chennai_Chemicals       True
Indi_Services          False
Chennai_Shipping        True
Eastern_Estates        False
Central_Services       False
Deccan_Sporting        False
Bangalore_Breweries    False
Bombay_Finance          True
NCR_Infra              False
Name: Sector, dtype: bool

In [49]:
df1[mask]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,NaN,874.4,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Chennai_Chemicals,966.0,863.2,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Chennai_Shipping,899.0,821.0,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Bombay_Finance,954.0,917.0,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$

In [50]:
df1[df1.Sector == 'Pub']

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,NaN,874.4,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Chennai_Chemicals,966.0,863.2,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Chennai_Shipping,899.0,821.0,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Bombay_Finance,954.0,917.0,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$

In [51]:
df1['Sector'].unique()

<StringArray>
['Pub', 'Gov', 'Prvt']
Length: 3, dtype: str

In [52]:
df1['GST'].unique()

<StringArray>
['Goods', 'Services']
Length: 2, dtype: str

In [53]:
df1[ (df1.Sector == 'Pub') & (df1.GST == 'Services')]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bombay_Finance,954.0,917.0,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$

In [54]:
df1["HQ"].unique()

<StringArray>
['Kol', 'NCR', 'Blr', 'Che', 'Hyd', 'Mum']
Length: 6, dtype: str

In [55]:
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,NaN,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921.0,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [56]:
df1['Profit'] = df1.Rev - df1.Exp

In [57]:
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Kolkata_FMCG,NaN,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,198.40
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,258.50
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,231.60
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,255.20
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,100.00
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,-78.00
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,45.23
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,135.00
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,224.80
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,201.00
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,252.00
NCR_Infra,921.0,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,228.50

In [58]:
df1[df1.Profit < 0]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Chennai_Shipping,899.0,821.0,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,-78.0

In [59]:
df1[(df1.Rev-df1.Exp) < 0]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Chennai_Shipping,899.0,821.0,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,-78.0

In [60]:
df1.Rev.sum()

np.float64(10170.23)

In [61]:
df1.Rev.mean()

np.float64(847.5191666666666)

In [62]:
df1[df1.Rev > df1.Rev.mean()]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Kolkata_FMCG,NaN,874.4,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,198.4
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,258.5
Bangalore_Systems,900.0,881.6,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,231.6
Chennai_Chemicals,966.0,863.2,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,255.2
Bangalore_Breweries,966.0,875.0,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,201.0
Bombay_Finance,954.0,917.0,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,252.0

In [63]:
df1[df1.Rev > df1.Rev.mean()]['EmpCnt']

Kolkata_FMCG           1379
NCR_Leagles            1935
Bangalore_Systems      1361
Chennai_Chemicals      1656
Bangalore_Breweries     119
Bombay_Finance         1443
Name: EmpCnt, dtype: int64

In [64]:
df1.loc[df1.Rev > df1.Rev.mean(),  'EmpCnt']

Kolkata_FMCG           1379
NCR_Leagles            1935
Bangalore_Systems      1361
Chennai_Chemicals      1656
Bangalore_Breweries     119
Bombay_Finance         1443
Name: EmpCnt, dtype: int64

In [65]:
df1.loc[df1.Rev > df1.Rev.mean(),  ['EmpCnt','Exp'] ]

                     EmpCnt  Exp
Kolkata_FMCG           1379  676
NCR_Leagles            1935  605
Bangalore_Systems      1361  650
Chennai_Chemicals      1656  608
Bangalore_Breweries     119  674
Bombay_Finance         1443  665

In [66]:
df1.columns != 'EmpCnt'

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True])

In [67]:
df1.loc[df1.Rev > df1.Rev.mean(),  df1.columns != 'EmpCnt' ]

,Vol,Rev,Exp,Sector,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Kolkata_FMCG,NaN,874.4,676,Pub,Kol,0,KFMC,Goods,Jan 1920,29.76$,198.4
NCR_Leagles,931.0,863.5,605,Pub,NCR,0,NCRL,Services,Feb 1960,38.78$,258.5
Bangalore_Systems,900.0,881.6,650,Gov,Blr,0,BSYS,Services,Apr 1950,34.74$,231.6
Chennai_Chemicals,966.0,863.2,608,Pub,Che,1,CHEM,Goods,Aug 1928,38.28$,255.2
Bangalore_Breweries,966.0,875.0,674,Prvt,Blr,1,BREW,Goods,Oct 1971,19.65$,201.0
Bombay_Finance,954.0,917.0,665,Pub,Mum,0,BFIN,Services,Apr 1925,37.8$,252.0

Grammer

Direct Access Mode

    df1[col_label]  or df1.col_label
    df1[ [list of col labels]  ]
    df1[ row_label1 : row_label2 ]

Integer Location Based Access
    df1.iloc[row_n_index]
    df1.iloc[row_n_index, col_n_index]

    df1.iloc[row_n_slice]
    df1.iloc[row_n_slice, col_n_slice]

    df1.iloc[ [list of row n indices] ]
    df1.iloc[ [list of row n indices], [list of col n indices] ]
    
    combo of above

Label Based Access
    df1.loc[row_label]
    df1.loc[row_label, col_label]

    df1.loc[row_label_slice]
    df1.loc[row_label_slice, col_label_slice]

    df1.loc[ [list of row_labels] ]
    df1.loc[ [list of row_labels], [list of col_labels] ]
    
    df1.loc[ boolean series of len being number of observation, boolean series of len being number of features]
    
     combo of above

In [68]:
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Kolkata_FMCG,NaN,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,198.40
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,258.50
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,231.60
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,255.20
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,100.00
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,-78.00
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,45.23
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,135.00
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,224.80
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,201.00
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,252.00
NCR_Infra,921.0,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,228.50

In [69]:
df1.head(3)

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Kolkata_FMCG,NaN,874.4,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,198.4
NCR_Leagles,931.0,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,258.5
Bangalore_Systems,900.0,881.6,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,231.6

In [70]:
df1.tail(3)

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Bangalore_Breweries,966.0,875.0,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,201.0
Bombay_Finance,954.0,917.0,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,252.0
NCR_Infra,921.0,843.5,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,228.5

In [71]:
df1.shape

(12, 12)

In [72]:
df1.ndim

2

In [73]:
df1.index

Index(['Kolkata_FMCG', 'NCR_Leagles', 'Bangalore_Systems', 'Chennai_Chemicals',
       'Indi_Services', 'Chennai_Shipping', 'Eastern_Estates',
       'Central_Services', 'Deccan_Sporting', 'Bangalore_Breweries',
       'Bombay_Finance', 'NCR_Infra'],
      dtype='str')

In [74]:
df1.columns

Index(['Vol', 'Rev', 'Exp', 'Sector', 'EmpCnt', 'HQ', 'MNC', 'StockID', 'GST',
       'Start Date', 'Taxpaid', 'Profit'],
      dtype='str')

In [75]:
df1.values

array([[nan, 874.4, 676, 'Pub', 1379, 'Kol', 0, 'KFMC', 'Goods',
        'Jan 1920', '29.76$', 198.39999999999998],
       [931.0, 863.5, 605, 'Pub', 1935, 'NCR', 0, 'NCRL', 'Services',
        'Feb 1960', '38.78$', 258.5],
       [900.0, 881.6, 650, 'Gov', 1361, 'Blr', 0, 'BSYS', 'Services',
        'Apr 1950', '34.74$', 231.60000000000002],
       [966.0, 863.2, 608, 'Pub', 1656, 'Che', 1, 'CHEM', 'Goods',
        'Aug 1928', '38.28$', 255.20000000000005],
       [992.0, 733.0, 633, 'Gov', 13023, 'NCR', 0, 'INDI', 'Services',
        'Mar 1920', '15$', 100.0],
       [899.0, 821.0, 899, 'Pub', 899, 'Che', 1, 'SHIP', 'Goods',
        'Nov 1930', '0', -78.0],
       [945.0, 834.23, 789, 'Prvt', 1873, 'Kol', 1, 'EEST', 'Goods',
        'Jan 1994', '6.78$', 45.23000000000002],
       [934.0, 824.0, 689, 'Gov', 1573, 'NCR', 1, 'CSRV', 'Services',
        'Jun 1974', '20.25$', 135.0],
       [931.0, 839.8, 615, 'Prvt', 154, 'Hyd', 1, 'SPRT', 'Services',
        'Mar 1943', '33.72$', 224.79999999999995],
       [966.0, 875.0, 674, 'Prvt', 119, 'Blr', 1, 'BREW', 'Goods',
        'Oct 1971', '19.65$', 201.0],
       [954.0, 917.0, 665, 'Pub', 1443, 'Mum', 0, 'BFIN', 'Services',
        'Apr 1925', '37.8$', 252.0],
       [921.0, 843.5, 615, 'Prvt', 1635, 'NCR', 0, 'NCIN', 'Services',
        'Feb 1920', '34.27$', 228.5]], dtype=object)

In [76]:
df1.info()

<class 'pandas.DataFrame'>
Index: 12 entries, Kolkata_FMCG to NCR_Infra
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Vol         11 non-null     float64
 1   Rev         12 non-null     float64
 2   Exp         12 non-null     int64
 3   Sector      12 non-null     str
 4   EmpCnt      12 non-null     int64
 5   HQ          12 non-null     str
 6   MNC         12 non-null     int64
 7   StockID     12 non-null     str
 8   GST         12 non-null     str
 9   Start Date  12 non-null     str
 10  Taxpaid     12 non-null     str
 11  Profit      12 non-null     float64
dtypes: float64(3), int64(3), str(6)
memory usage: 1.5+ KB

In [77]:
df1.describe()

              Vol         Rev         Exp        EmpCnt        MNC      Profit
count   11.000000   12.000000   12.000000     12.000000  12.000000   12.000000
mean   939.909091  847.519167  676.500000   2254.166667   0.500000  171.019167
std     28.490190   45.318608   86.561066   3443.674751   0.522233  103.126925
min    899.000000  733.000000  605.000000    119.000000   0.000000  -78.000000
25%    926.000000  831.672500  615.000000   1245.500000   0.000000  126.250000
50%    934.000000  853.350000  657.500000   1508.000000   0.500000  212.900000
75%    960.000000  874.550000  679.250000   1710.250000   1.000000  236.700000
max    992.000000  917.000000  899.000000  13023.000000   1.000000  258.500000

In [78]:
df1.describe(include='all')

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
count,11.000000,12.000000,12.000000,12,12.000000,12,12.000000,12,12,12,12,12.000000
unique,NaN,NaN,NaN,3,NaN,6,NaN,12,2,12,12,NaN
top,NaN,NaN,NaN,Pub,NaN,NCR,NaN,KFMC,Services,Jan 1920,29.76$,NaN
freq,NaN,NaN,NaN,5,NaN,4,NaN,1,7,1,1,NaN
mean,939.909091,847.519167,676.500000,NaN,2254.166667,NaN,0.500000,NaN,NaN,NaN,NaN,171.019167
std,28.490190,45.318608,86.561066,NaN,3443.674751,NaN,0.522233,NaN,NaN,NaN,NaN,103.126925
min,899.000000,733.000000,605.000000,NaN,119.000000,NaN,0.000000,NaN,NaN,NaN,NaN,-78.000000
25%,926.000000,831.672500,615.000000,NaN,1245.500000,NaN,0.000000,NaN,NaN,NaN,NaN,126.250000
50%,934.000000,853.350000,657.500000,NaN,1508.000000,NaN,0.500000,NaN,NaN,NaN,NaN,212.900000
75%,960.000000,874.550000,679.250000,NaN,1710.250000,NaN,1.000000,NaN,NaN,NaN,NaN,236.700000
max,992.000000,917.000000,899.000000,NaN,13023.000000,NaN,1.000000,NaN,NaN,NaN,NaN,258.500000

In [79]:
df1.describe(include=np.int64)

              Exp        EmpCnt        MNC
count   12.000000     12.000000  12.000000
mean   676.500000   2254.166667   0.500000
std     86.561066   3443.674751   0.522233
min    605.000000    119.000000   0.000000
25%    615.000000   1245.500000   0.000000
50%    657.500000   1508.000000   0.500000
75%    679.250000   1710.250000   1.000000
max    899.000000  13023.000000   1.000000

In [80]:
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Profit
Kolkata_FMCG,NaN,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,198.40
NCR_Leagles,931.0,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,258.50
Bangalore_Systems,900.0,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,231.60
Chennai_Chemicals,966.0,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,255.20
Indi_Services,992.0,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,100.00
Chennai_Shipping,899.0,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,-78.00
Eastern_Estates,945.0,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,45.23
Central_Services,934.0,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,135.00
Deccan_Sporting,931.0,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,224.80
Bangalore_Breweries,966.0,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,201.00
Bombay_Finance,954.0,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,252.00
NCR_Infra,921.0,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,228.50

In [81]:
df1.Sector.count()

np.int64(12)

In [82]:
df1.Sector.value_counts()

Sector
Pub     5
Prvt    4
Gov     3
Name: count, dtype: int64

In [83]:
df1.Rev.max()

np.float64(917.0)

In [84]:
df1.Rev.min()

np.float64(733.0)

In [85]:
df1.Rev.mean()

np.float64(847.5191666666666)

In [86]:
df1.Rev.std()

np.float64(45.31860794988249)

In [87]:
df1.Rev.var()

np.float64(2053.7762265151523)

In [88]:
df1['Rev'].var()

np.float64(2053.7762265151523)

# Saving  the DF

In [90]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [91]:
df1.to_csv('file1.csv')

In [93]:
df1.to_html('file1.html')

In [94]:
df1.to_json('file1.json')

In [95]:
df10 = pd.read_csv('file1.csv', index_col=0)
df10

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [ ]:
df12 = pd.read_json('file1.json')
df12

# Sorting

In [98]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [39]:
df2 = df1.sort_index(axis=0, inplace=False)
print(df2)

                     Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Bangalore_Breweries  966  875.00  674   Prvt     119  Blr    1    BREW
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS
Bombay_Finance       954  917.00  665    Pub    1443  Mum    0    BFIN
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM
Chennai_Shipping     899  821.00  899    Pub     899  Che    1    SHIP
Deccan_Sporting      931  839.80  615   Prvt     154  Hyd    1    SPRT
Eastern_Estates      945  834.23  789   Prvt    1873  Kol    1    EEST
Indi_Services        992  733.00  633    Gov   13023  NCR    0    INDI
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC
NCR_Infra            921  843.50  615   Prvt    1635  NCR    0    NCIN
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL

                          GST Start Date Taxpaid
Bangalore_Breweries     Goods   Oct 1971  19.65$
Bangalore_Systems    Services   Apr 1950  34.74$
Bombay_Finance       Services   Apr 1925   37.8$
Central_Services     Services   Jun 1974  20.25$
Chennai_Chemicals       Goods   Aug 1928  38.28$
Chennai_Shipping        Goods   Nov 1930       0
Deccan_Sporting      Services   Mar 1943  33.72$
Eastern_Estates         Goods   Jan 1994   6.78$
Indi_Services        Services   Mar 1920     15$
Kolkata_FMCG            Goods   Jan 1920  29.76$
NCR_Infra            Services   Feb 1920  34.27$
NCR_Leagles          Services   Feb 1960  38.78$

In [ ]:
df1

In [41]:
df3 = df1.sort_index(axis=1, inplace=False)
df3

,EmpCnt,Exp,GST,HQ,MNC,Rev,Sector,Start Date,StockID,Taxpaid,Vol
Kolkata_FMCG,1379,676,Goods,Kol,0,874.40,Pub,Jan 1920,KFMC,29.76$,925
NCR_Leagles,1935,605,Services,NCR,0,863.50,Pub,Feb 1960,NCRL,38.78$,931
Bangalore_Systems,1361,650,Services,Blr,0,881.60,Gov,Apr 1950,BSYS,34.74$,900
Chennai_Chemicals,1656,608,Goods,Che,1,863.20,Pub,Aug 1928,CHEM,38.28$,966
Indi_Services,13023,633,Services,NCR,0,733.00,Gov,Mar 1920,INDI,15$,992
Chennai_Shipping,899,899,Goods,Che,1,821.00,Pub,Nov 1930,SHIP,0,899
Eastern_Estates,1873,789,Goods,Kol,1,834.23,Prvt,Jan 1994,EEST,6.78$,945
Central_Services,1573,689,Services,NCR,1,824.00,Gov,Jun 1974,CSRV,20.25$,934
Deccan_Sporting,154,615,Services,Hyd,1,839.80,Prvt,Mar 1943,SPRT,33.72$,931
Bangalore_Breweries,119,674,Goods,Blr,1,875.00,Prvt,Oct 1971,BREW,19.65$,966
Bombay_Finance,1443,665,Services,Mum,0,917.00,Pub,Apr 1925,BFIN,37.8$,954
NCR_Infra,1635,615,Services,NCR,0,843.50,Prvt,Feb 1920,NCIN,34.27$,921

In [ ]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1 = df1.sort_index(axis=0, inplace=False).sort_index(axis=1, inplace=False)
df1

In [ ]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

In [15]:
df1.sort_values(by='Vol',ascending=True)

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$

In [16]:
df1.sort_values(by=['Vol','Rev'],ascending=True)

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$

In [ ]:
df1.sort_values(by=['Vol','Rev'],ascending=[True,False])

In [ ]:
df1.sort_values(by='NCR_Leagles',ascending=True, axis=1) # will not work. heterogenous values

# Ranking

In [3]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [12]:
df1['rank'] = df1.Vol.rank(ascending=False, method='average')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,rank
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,9.0
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,7.5
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,11.0
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,2.5
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,1.0
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,12.0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,5.0
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,6.0
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,7.5
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,2.5
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,4.0
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,10.0

In [13]:
df1['rank'] = df1.Vol.rank(ascending=False, method='first')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,rank
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,9.0
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,7.0
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,11.0
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,2.0
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,1.0
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,12.0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,5.0
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,6.0
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,8.0
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,3.0
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,4.0
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,10.0

In [14]:
df1['rank'] = df1.Vol.rank(ascending=False, method='min')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,rank
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,9.0
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,7.0
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,11.0
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,2.0
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,1.0
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,12.0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,5.0
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,6.0
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,7.0
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,2.0
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,4.0
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,10.0

In [15]:
df1['rank'] = df1.Vol.rank(ascending=False, method='max')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,rank
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,9.0
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,8.0
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,11.0
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,3.0
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,1.0
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,12.0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,5.0
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,6.0
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,8.0
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,3.0
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,4.0
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,10.0

In [16]:
df1['rank'] = df1.Vol.rank(ascending=False, method='dense')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,rank
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,7.0
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,6.0
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,9.0
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,2.0
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,1.0
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,10.0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,4.0
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,5.0
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,6.0
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,2.0
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,3.0
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,8.0

# Concatenation

In [4]:
df11 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds11.csv')
df11

                 Vol    Rev  Exp Sector  EmpCnt
Kolkata_FMCG     900  874.4  676    Pub    1379
NCR_Leagles      931  863.5  605    Pub    1935
Bombay_Sporting  975  839.8  615    Pvt     154

In [5]:
df12 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds12.csv')
df12

                   Vol    Rev  Exp Sector   HQ
Bombay_Sporting    925  839.8  715    Pvt  Mum
Bombay_Finance     899  917.0  674    Pub  Mum
Bangalore_Systems  931  881.6  650    Gov  Blr
Chennai_Shipping   992  821.0  665    Pub  Che

In [6]:
df13 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds13.csv')
df13

                     Vol    Rev  Exp Sector  EmpCnt   HQ
Bangalore_Breweries  966  805.0  895    Pvt     119  Blr
Chennai_Chemicals    966  863.2  608    Pub    1656  Che
Indi_Services        954  733.0  609    Gov   13023  NCR

In [7]:
dfc = pd.concat(objs=(df11,df12),join='outer',axis=0)
dfc

                   Vol    Rev  Exp Sector  EmpCnt   HQ
Kolkata_FMCG       900  874.4  676    Pub  1379.0  NaN
NCR_Leagles        931  863.5  605    Pub  1935.0  NaN
Bombay_Sporting    975  839.8  615    Pvt   154.0  NaN
Bombay_Sporting    925  839.8  715    Pvt     NaN  Mum
Bombay_Finance     899  917.0  674    Pub     NaN  Mum
Bangalore_Systems  931  881.6  650    Gov     NaN  Blr
Chennai_Shipping   992  821.0  665    Pub     NaN  Che

In [8]:
dfc = pd.concat(objs=(df11,df12),join='inner',axis=0)
dfc

                   Vol    Rev  Exp Sector
Kolkata_FMCG       900  874.4  676    Pub
NCR_Leagles        931  863.5  605    Pub
Bombay_Sporting    975  839.8  615    Pvt
Bombay_Sporting    925  839.8  715    Pvt
Bombay_Finance     899  917.0  674    Pub
Bangalore_Systems  931  881.6  650    Gov
Chennai_Shipping   992  821.0  665    Pub

In [21]:
dfc = pd.concat(objs=(df11,df12),join='inner',axis=0,  keys=['frame11', 'frame12'])
dfc

                           Vol    Rev  Exp Sector
frame11 Kolkata_FMCG       900  874.4  676    Pub
        NCR_Leagles        931  863.5  605    Pub
        Bombay_Sporting    975  839.8  615    Pvt
frame12 Bombay_Sporting    925  839.8  715    Pvt
        Bombay_Finance     899  917.0  674    Pub
        Bangalore_Systems  931  881.6  650    Gov
        Chennai_Shipping   992  821.0  665    Pub

In [22]:
dfc.index

MultiIndex([('frame11',      'Kolkata_FMCG'),
            ('frame11',       'NCR_Leagles'),
            ('frame11',   'Bombay_Sporting'),
            ('frame12',   'Bombay_Sporting'),
            ('frame12',    'Bombay_Finance'),
            ('frame12', 'Bangalore_Systems'),
            ('frame12',  'Chennai_Shipping')],
           )

In [ ]:
dfc.loc[('frame12',    'Bombay_Finance'),'Rev']

In [23]:
dfc = pd.concat(objs=(df11,df12),join='outer',axis=1)
dfc

,Vol,Rev,Exp,Sector,EmpCnt,Vol,Rev,Exp,Sector,HQ
Kolkata_FMCG,900.0,874.4,676.0,Pub,1379.0,NaN,NaN,NaN,NaN,NaN
NCR_Leagles,931.0,863.5,605.0,Pub,1935.0,NaN,NaN,NaN,NaN,NaN
Bombay_Sporting,975.0,839.8,615.0,Pvt,154.0,925.0,839.8,715.0,Pvt,Mum
Bombay_Finance,NaN,NaN,NaN,NaN,NaN,899.0,917.0,674.0,Pub,Mum
Bangalore_Systems,NaN,NaN,NaN,NaN,NaN,931.0,881.6,650.0,Gov,Blr
Chennai_Shipping,NaN,NaN,NaN,NaN,NaN,992.0,821.0,665.0,Pub,Che

In [24]:
dfc = pd.concat(objs=(df11,df12),join='inner',axis=1,  keys=['frame11', 'frame12'])
dfc

                frame11                           frame12                     \
                    Vol    Rev  Exp Sector EmpCnt     Vol    Rev  Exp Sector
Bombay_Sporting     975  839.8  615    Pvt    154     925  839.8  715    Pvt


                  HQ
Bombay_Sporting  Mum

In [ ]:
dfc.index

In [ ]:
dfc.columns

In [ ]:
dfc.loc['Bombay_Sporting',('frame12',    'Vol') ]

# Merge

## Merge Datasets

In [1]:
df21 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds21.csv')
df21

NameError: name 'pd' is not defined

In [10]:
df22 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds22.csv')
df22

                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500

In [11]:
df23 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds23.csv')
df23

                    stock_name   HQ  empcnt
Chennai_Shipping          SHIP  Che   10000
Bangalore_Breweries       BREW  Blr    5000
Bombay_Finance            BFIN  Mum   30000
Bangalore_Systems         BSYS  Blr   20000

In [28]:
print(df21)
print(df22)
print()
dfm = pd.merge(df21,df22, how='inner', on='HQ', indicator=True)
print(dfm)

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500

  stock_id   HQ  high stock_name  vol _merge
0     BREW  Blr  1100       BREW  350   both
1     SHIP  Che  1200       CHEM  550   both
2     KFMC  Kol  2000       KFMC  500   both

In [29]:
print(df21)
print(df22)
print()
dfm = pd.merge(df21,df22, how='outer', on='HQ', indicator=True)
print(dfm)

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500

  stock_id   HQ    high stock_name    vol      _merge
0     BREW  Blr  1100.0       BREW  350.0        both
1     SHIP  Che  1200.0       CHEM  550.0        both
2     KFMC  Kol  2000.0       KFMC  500.0        both
3      NaN  Mum     NaN       BFIN  450.0  right_only
4     NCRL  NCR  1200.0        NaN    NaN   left_only

In [30]:
print(df21)
print(df22)
print()
dfm = pd.merge(df21,df22, how='left', on='HQ', indicator=True)
print(dfm)

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500

  stock_id   HQ  high stock_name    vol     _merge
0     BREW  Blr  1100       BREW  350.0       both
1     SHIP  Che  1200       CHEM  550.0       both
2     KFMC  Kol  2000       KFMC  500.0       both
3     NCRL  NCR  1200        NaN    NaN  left_only

In [31]:
print(df21)
print(df22)
print()
dfm = pd.merge(df21,df22, how='right', on='HQ', indicator=True)
print(dfm)

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500

  stock_id   HQ    high stock_name  vol      _merge
0     BREW  Blr  1100.0       BREW  350        both
1      NaN  Mum     NaN       BFIN  450  right_only
2     SHIP  Che  1200.0       CHEM  550        both
3     KFMC  Kol  2000.0       KFMC  500        both

In [47]:
print(df21)
print(df22)
print()
dfm = pd.merge(df21,df22, how='cross',indicator=True)
print(dfm)

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500

   stock_id HQ_x  high stock_name HQ_y  vol _merge
0      BREW  Blr  1100       BREW  Blr  350   both
1      BREW  Blr  1100       BFIN  Mum  450   both
2      BREW  Blr  1100       CHEM  Che  550   both
3      BREW  Blr  1100       KFMC  Kol  500   both
4      SHIP  Che  1200       BREW  Blr  350   both
5      SHIP  Che  1200       BFIN  Mum  450   both
6      SHIP  Che  1200       CHEM  Che  550   both
7      SHIP  Che  1200       KFMC  Kol  500   both
8      KFMC  Kol  2000       BREW  Blr  350   both
9      KFMC  Kol  2000       BFIN  Mum  450   both
10     KFMC  Kol  2000       CHEM  Che  550   both
11     KFMC  Kol  2000       KFMC  Kol  500   both
12     NCRL  NCR  1200       BREW  Blr  350   both
13     NCRL  NCR  1200       BFIN  Mum  450   both
14     NCRL  NCR  1200       CHEM  Che  550   both
15     NCRL  NCR  1200       KFMC  Kol  500   both

In [12]:
print(df22)
print(df23)
print()
dfm = pd.merge(df22,df23, how='inner',on='HQ', indicator=True)
print(dfm)

                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500
                    stock_name   HQ  empcnt
Chennai_Shipping          SHIP  Che   10000
Bangalore_Breweries       BREW  Blr    5000
Bombay_Finance            BFIN  Mum   30000
Bangalore_Systems         BSYS  Blr   20000

  stock_name_x   HQ  vol stock_name_y  empcnt _merge
0         BREW  Blr  350         BREW    5000   both
1         BREW  Blr  350         BSYS   20000   both
2         BFIN  Mum  450         BFIN   30000   both
3         CHEM  Che  550         SHIP   10000   both

In [15]:
print(df21)
print(df22)
print()
dfm = pd.merge(df21,df22, how='inner',left_on='stock_id', 
               right_on='stock_name',indicator=True)
print(dfm)

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500

  stock_id HQ_x  high stock_name HQ_y  vol _merge
0     BREW  Blr  1100       BREW  Blr  350   both
1     KFMC  Kol  2000       KFMC  Kol  500   both

# Rename of Indices

In [ ]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

In [ ]:
df1.rename(index={'Indi_Services':'IR','Bangalore_Breweries':'UB' }, 
           columns={'Vol':'Volume','abc':'xyz'})

# Pivot Table

In [16]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [43]:
pd.pivot_table(df1, index='Sector')

TypeError: agg function failed [how->mean,dtype->object]

In [20]:
dfp = pd.pivot_table(df1, index='Sector', values=['Vol','Exp','Rev'])
dfp

               Exp         Rev     Vol
Sector
Gov     657.333333  812.866667  942.00
Prvt    673.250000  848.132500  940.75
Pub     690.600000  867.820000  935.00

In [19]:
dfp.index

Index(['Gov', 'Prvt', 'Pub'], dtype='object', name='Sector')

In [21]:
dfp.columns

Index(['Exp', 'Rev', 'Vol'], dtype='object')

In [48]:
dfp = pd.pivot_table(df1, index=['Sector','GST'], values=['Vol','Exp','Rev'])
dfp

                        Exp         Rev    Vol
Sector GST
Gov    Services  657.333333  812.866667  942.0
Prvt   Goods     731.500000  854.615000  955.5
       Services  615.000000  841.650000  926.0
Pub    Goods     727.666667  852.866667  930.0
       Services  635.000000  890.250000  942.5

In [ ]:
dfp.index

In [46]:
dfp = pd.pivot_table(df1, index=['Sector','GST'], values=['Vol','Exp','Rev'], aggfunc='mean')
dfp

                        Exp         Rev    Vol
Sector GST
Gov    Services  657.333333  812.866667  942.0
Prvt   Goods     731.500000  854.615000  955.5
       Services  615.000000  841.650000  926.0
Pub    Goods     727.666667  852.866667  930.0
       Services  635.000000  890.250000  942.5

In [49]:
dfp = pd.pivot_table(df1, index=['Sector','GST'], values=['Vol','Exp','Rev'], 
                     aggfunc=['mean','max','count'])
dfp

                       mean                     max             count
                        Exp         Rev    Vol  Exp    Rev  Vol   Exp Rev Vol
Sector GST
Gov    Services  657.333333  812.866667  942.0  689  881.6  992     3   3   3
Prvt   Goods     731.500000  854.615000  955.5  789  875.0  966     2   2   2
       Services  615.000000  841.650000  926.0  615  843.5  931     2   2   2
Pub    Goods     727.666667  852.866667  930.0  899  874.4  966     3   3   3
       Services  635.000000  890.250000  942.5  665  917.0  954     2   2   2

In [26]:
dfp = pd.pivot_table(df1, index=['Sector','GST'], 
                     values=['Vol','Exp','Rev'], 
                     aggfunc=['min','max',np.sum])
dfp

C:\Users\Edunet Foundation\AppData\Local\Temp\ipykernel_42960\285240889.py:1: FutureWarning: The provided callable <function sum at 0x000001BE906B7EC0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  dfp = pd.pivot_table(df1, index=['Sector','GST'],

                 min               max               sum
                 Exp     Rev  Vol  Exp    Rev  Vol   Exp      Rev   Vol
Sector GST
Gov    Services  633  733.00  900  689  881.6  992  1972  2438.60  2826
Prvt   Goods     674  834.23  945  789  875.0  966  1463  1709.23  1911
       Services  615  839.80  921  615  843.5  931  1230  1683.30  1852
Pub    Goods     608  821.00  899  899  874.4  966  2183  2558.60  2790
       Services  605  863.50  931  665  917.0  954  1270  1780.50  1885

In [24]:
def maxmindiff(c):
    print(c)
    print(type(c))
    print()
    return c.max()-c.min()

In [25]:
dfp = pd.pivot_table(df1, index=['Sector','GST'], 
                     values=['Vol','Exp','Rev'], 
                     aggfunc=[np.min,'max',maxmindiff])
dfp

Bangalore_Systems    900
Indi_Services        992
Central_Services     934
Name: Vol, dtype: int64
<class 'pandas.core.series.Series'>

Eastern_Estates        945
Bangalore_Breweries    966
Name: Vol, dtype: int64
<class 'pandas.core.series.Series'>

Deccan_Sporting    931
NCR_Infra          921
Name: Vol, dtype: int64
<class 'pandas.core.series.Series'>

Kolkata_FMCG         925
Chennai_Chemicals    966
Chennai_Shipping     899
Name: Vol, dtype: int64
<class 'pandas.core.series.Series'>

NCR_Leagles       931
Bombay_Finance    954
Name: Vol, dtype: int64
<class 'pandas.core.series.Series'>

Bangalore_Systems    650
Indi_Services        633
Central_Services     689
Name: Exp, dtype: int64
<class 'pandas.core.series.Series'>

Eastern_Estates        789
Bangalore_Breweries    674
Name: Exp, dtype: int64
<class 'pandas.core.series.Series'>

Deccan_Sporting    615
NCR_Infra          615
Name: Exp, dtype: int64
<class 'pandas.core.series.Series'>

Kolkata_FMCG         676
Chennai_Chemicals    608
Chennai_Shipping     899
Name: Exp, dtype: int64
<class 'pandas.core.series.Series'>

NCR_Leagles       605
Bombay_Finance    665
Name: Exp, dtype: int64
<class 'pandas.core.series.Series'>

Bangalore_Systems    881.6
Indi_Services        733.0
Central_Services     824.0
Name: Rev, dtype: float64
<class 'pandas.core.series.Series'>

Eastern_Estates        834.23
Bangalore_Breweries    875.00
Name: Rev, dtype: float64
<class 'pandas.core.series.Series'>

Deccan_Sporting    839.8
NCR_Infra          843.5
Name: Rev, dtype: float64
<class 'pandas.core.series.Series'>

Kolkata_FMCG         874.4
Chennai_Chemicals    863.2
Chennai_Shipping     821.0
Name: Rev, dtype: float64
<class 'pandas.core.series.Series'>

NCR_Leagles       863.5
Bombay_Finance    917.0
Name: Rev, dtype: float64
<class 'pandas.core.series.Series'>

C:\Users\Edunet Foundation\AppData\Local\Temp\ipykernel_42960\3785138593.py:1: FutureWarning: The provided callable <function min at 0x000001BEA66D0720> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  dfp = pd.pivot_table(df1, index=['Sector','GST'],

                 min               max             maxmindiff
                 Exp     Rev  Vol  Exp    Rev  Vol        Exp     Rev Vol
Sector GST
Gov    Services  633  733.00  900  689  881.6  992         56  148.60  92
Prvt   Goods     674  834.23  945  789  875.0  966        115   40.77  21
       Services  615  839.80  921  615  843.5  931          0    3.70  10
Pub    Goods     608  821.00  899  899  874.4  966        291   53.40  67
       Services  605  863.50  931  665  917.0  954         60   53.50  23

In [22]:
df1[(df1.Sector == 'Pub') & (df1.GST == 'Services')]['Vol']

NCR_Leagles       931
Bombay_Finance    954
Name: Vol, dtype: int64

In [ ]:
dfp = pd.pivot_table(df1, index=['Sector','GST'], 
                     values='Vol', 
                     aggfunc=maxmindiff)
dfp

In [ ]:
dfp = pd.pivot_table(df1, index=['Sector','GST'], 
                     values='Vol', 
                     aggfunc=lambda c: c.max()-c.min())
dfp

In [ ]:
# what is the minimum revenue of pub companies in chennai
dfp = pd.pivot_table(df1, index='Sector',
                     columns='HQ',
                     values=['Vol','Rev'], 
                     aggfunc=['min','max'])
dfp

In [ ]:
print(type(dfp))

# Groupby

In [51]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [52]:
df1.Sector.value_counts()

Sector
Pub     5
Prvt    4
Gov     3
Name: count, dtype: int64

In [53]:
df1.Sector.value_counts()

Sector
Pub     5
Prvt    4
Gov     3
Name: count, dtype: int64

In [54]:
dfg = df1.groupby(by='Sector')
print(type(dfg))
print()
for item in dfg:
    print(item)
    print()

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

('Gov',                    Vol    Rev  Exp Sector  EmpCnt   HQ  MNC StockID       GST  \
Bangalore_Systems  900  881.6  650    Gov    1361  Blr    0    BSYS  Services
Indi_Services      992  733.0  633    Gov   13023  NCR    0    INDI  Services
Central_Services   934  824.0  689    Gov    1573  NCR    1    CSRV  Services

                  Start Date Taxpaid
Bangalore_Systems   Apr 1950  34.74$
Indi_Services       Mar 1920     15$
Central_Services    Jun 1974  20.25$  )

('Prvt',                      Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Eastern_Estates      945  834.23  789   Prvt    1873  Kol    1    EEST
Deccan_Sporting      931  839.80  615   Prvt     154  Hyd    1    SPRT
Bangalore_Breweries  966  875.00  674   Prvt     119  Blr    1    BREW
NCR_Infra            921  843.50  615   Prvt    1635  NCR    0    NCIN

                          GST Start Date Taxpaid
Eastern_Estates         Goods   Jan 1994   6.78$
Deccan_Sporting      Services   Mar 1943  33.72$
Bangalore_Breweries     Goods   Oct 1971  19.65$
NCR_Infra            Services   Feb 1920  34.27$  )

('Pub',                    Vol    Rev  Exp Sector  EmpCnt   HQ  MNC StockID       GST  \
Kolkata_FMCG       925  874.4  676    Pub    1379  Kol    0    KFMC     Goods
NCR_Leagles        931  863.5  605    Pub    1935  NCR    0    NCRL  Services
Chennai_Chemicals  966  863.2  608    Pub    1656  Che    1    CHEM     Goods
Chennai_Shipping   899  821.0  899    Pub     899  Che    1    SHIP     Goods
Bombay_Finance     954  917.0  665    Pub    1443  Mum    0    BFIN  Services

                  Start Date Taxpaid
Kolkata_FMCG        Jan 1920  29.76$
NCR_Leagles         Feb 1960  38.78$
Chennai_Chemicals   Aug 1928  38.28$
Chennai_Shipping    Nov 1930       0
Bombay_Finance      Apr 1925   37.8$  )

In [55]:
dfg = df1.groupby(by='Sector')  
list(dfg)[0][-1]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Bangalore_Systems,900,881.6,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Indi_Services,992,733.0,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Central_Services,934,824.0,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$

In [56]:
df1.groupby(by='Sector').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [57]:
df1.groupby(by='Sector')['Vol'].mean()

Sector
Gov     942.00
Prvt    940.75
Pub     935.00
Name: Vol, dtype: float64

In [58]:
df1.groupby(by='Sector')[['Vol','Rev']].mean()

           Vol         Rev
Sector
Gov     942.00  812.866667
Prvt    940.75  848.132500
Pub     935.00  867.820000

In [59]:
df1.groupby(by='Sector')[['Vol','Rev']].agg(['mean','min'])

           Vol              Rev
          mean  min        mean     min
Sector
Gov     942.00  900  812.866667  733.00
Prvt    940.75  921  848.132500  834.23
Pub     935.00  899  867.820000  821.00

In [60]:
df1.groupby(by=['Sector','GST'])[['Vol','Rev']].agg(['mean','min'])

                   Vol              Rev
                  mean  min        mean     min
Sector GST
Gov    Services  942.0  900  812.866667  733.00
Prvt   Goods     955.5  945  854.615000  834.23
       Services  926.0  921  841.650000  839.80
Pub    Goods     930.0  899  852.866667  821.00
       Services  942.5  931  890.250000  863.50

# Map

In [27]:
df1 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds1.csv')
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$

In [28]:
md1 = {'Kol':'EZ', 'Mum':'WZ','Che':'SZ','Blr':'SZ','NCR':'NZ'}

In [30]:
df1['Zone'] = df1.HQ.map(md1)
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date,Taxpaid,Zone
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920,29.76$,EZ
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960,38.78$,NZ
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950,34.74$,SZ
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928,38.28$,SZ
Indi_Services,992,733.00,633,Gov,13023,NCR,0,INDI,Services,Mar 1920,15$,NZ
Chennai_Shipping,899,821.00,899,Pub,899,Che,1,SHIP,Goods,Nov 1930,0,SZ
Eastern_Estates,945,834.23,789,Prvt,1873,Kol,1,EEST,Goods,Jan 1994,6.78$,EZ
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974,20.25$,NZ
Deccan_Sporting,931,839.80,615,Prvt,154,Hyd,1,SPRT,Services,Mar 1943,33.72$,NaN
Bangalore_Breweries,966,875.00,674,Prvt,119,Blr,1,BREW,Goods,Oct 1971,19.65$,SZ
Bombay_Finance,954,917.00,665,Pub,1443,Mum,0,BFIN,Services,Apr 1925,37.8$,WZ
NCR_Infra,921,843.50,615,Prvt,1635,NCR,0,NCIN,Services,Feb 1920,34.27$,NZ

Sales_Performance

vol>935: 'Excellent_Sales
vol < 910 'Average_Sales'
'Good_Sales'

In [ ]:
def sales_query(sales_value):
    if sales_value > 955:
        return 'Excellent'
    elif sales_value < 910:
        return 'Average'
    else:
        return 'Good'

In [ ]:
df1['Sales_Performance'] = df1.Vol.map(sales_query)
df1

# Stack & Unstack

                      2021  2021   2022   2022
                       Q1   Q2      Q1    Q2


Tata     FMCG
Tata     Tech
Birla    FMCG
Birla    Tech
Wipro    FMCG
Wipro    Tech
ITC      FMCG
ITC      Tech
Reliance FMCG
Reliane  Tech

In [ ]:
col_level0 = [2021,2022]
col_level1 = ['Q1', 'Q2']
col_labels= pd.MultiIndex.from_product([col_level0, col_level1])

row_level0 = ['Tata','Birla','Wipro','ITC','Reliance']
row_level1 = ['FMCG', 'Tech']
row_labels= pd.MultiIndex.from_product([row_level0, row_level1])

np.random.seed(23)
n10x4 = np.random.randint(low=10, high=100,size=(10,4))

In [ ]:
df1 = pd.DataFrame(n10x4, index=row_labels, columns=col_labels)
df1

In [ ]:
df1.index

In [ ]:
df1.columns

In [ ]:
df1.loc[(   'Wipro', 'Tech'),(2022, 'Q1') ]

In [ ]:
df2 = df1.stack()
print(df2.index)
print(df2.columns)

In [ ]:
df2 = df1.unstack()
print(df2.index)
print(df2.columns)
df2

In [ ]:
df1

In [ ]:
df1.unstack(level=0).stack(level=-2).unstack(level=0).stack(level=-1).stack(level=0).unstack(level=-1)

In [ ]:
df1.stack(level=-1).unstack(level=0).stack(level=-1).unstack(level=-1)

In [ ]:
df1.stack(level=-1).unstack(level=0).unstack(level=0).stack(level=-1).stack(level=0).unstack(level=-1)

# Melting

In [31]:
df31 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds31.csv')
df31

    Location Temperature  Jan2019  Feb2019  Mar2019
0  Bangalore     Predict       23       25       28
1    Chennai      Actual       32       34       36

In [32]:
pd.melt(df31, id_vars=['Location', 'Temperature'])

    Location Temperature variable  value
0  Bangalore     Predict  Jan2019     23
1    Chennai      Actual  Jan2019     32
2  Bangalore     Predict  Feb2019     25
3    Chennai      Actual  Feb2019     34
4  Bangalore     Predict  Mar2019     28
5    Chennai      Actual  Mar2019     36

In [ ]:
pd.melt(df31, id_vars=['Location', 'Temperature'],
        value_name='melted_cols_values')

In [33]:
dfm  = pd.melt(df31, id_vars=['Location', 'Temperature'], 
        var_name = 'melted_cols_names',value_name='melted_cols_values')

In [34]:
dfm

    Location Temperature melted_cols_names  melted_cols_values
0  Bangalore     Predict           Jan2019                  23
1    Chennai      Actual           Jan2019                  32
2  Bangalore     Predict           Feb2019                  25
3    Chennai      Actual           Feb2019                  34
4  Bangalore     Predict           Mar2019                  28
5    Chennai      Actual           Mar2019                  36

# NaN Handling

In [ ]:
df0 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds0.csv')
df0

In [ ]:
df0.isna().sum().sum()

In [ ]:
df0.info()

In [ ]:
df0.isna().sum()

In [ ]:
df0.dropna()

In [ ]:
df0.Rev.fillna(850)

In [ ]:
df0.Rev.mean()

In [ ]:
df0.Rev.fillna(df0.Rev.mean(), inplace=True)

In [ ]:
df0.EmpCnt.mean()

In [ ]:
df0.EmpCnt.median()

In [ ]:
df0.EmpCnt.fillna(df0.EmpCnt.median(), inplace=True)

In [ ]:
df0.Sector.fillna(method='bfill')

In [ ]:
df0.Sector.fillna(method='ffill')

# Drop

In [ ]:
df0 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds0.csv')
df0

In [ ]:
df0.drop(columns=['Vol','Exp','HQ'],  
         index=['NCR_Leagles','Bombay_Finance'],
        inplace=True)
df0

# Drop Duplicates

In [35]:
df33 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds33.csv')
df33

        Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
1  15/2/2019  Shimla           12        65
2  15/3/2019  Shimla           11        57
3  15/1/2019  Shimla           11        67
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
6  15/1/2020    Pune           29        21
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

In [36]:
df33.duplicated(subset=None, keep='first')

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [37]:
df33.duplicated(subset=None, keep='last')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [38]:
df33.duplicated(subset=None, keep=False)

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [39]:
df33.duplicated(subset=['City','Temperature'], keep='first')

0    False
1    False
2     True
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [ ]:
df33[df33.duplicated(subset=['City','Temperature'], keep='first')]

In [40]:
print(df33)
df33.drop_duplicates(subset=['City','Temperature'], keep='first')

        Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
1  15/2/2019  Shimla           12        65
2  15/3/2019  Shimla           11        57
3  15/1/2019  Shimla           11        67
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
6  15/1/2020    Pune           29        21
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

        Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
1  15/2/2019  Shimla           12        65
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

In [ ]:
print(df33)
df33.drop_duplicates(subset=['City','Temperature'], keep='last')

In [ ]:
print(df33)
df33.drop_duplicates(subset=['City','Temperature'], keep=False)

# Replace

In [ ]:
df33 = pd.read_csv('https://raw.githubusercontent.com/vcsgithub/vcsgithub.github.io/master/lds33.csv')
df33

In [ ]:
df33.replace({'Pune':'Mumbai'})

In [ ]:
df33.City.replace({'Pune':'Nagpur'})